### DISCUSSION TITLE
Prometheus Metrics inside a k8s cluster

### DISCUSSION THREAD

**Discussion by 0x524c** [moleculerjs/moleculer#1232] [Q&A]
In my development environment I can read the metrics that I export to Prometheus. However, I would like an example of how to configure a service and other settings to be able to export in the k8s cluster. Can anyone help?

I am successfully running a Moleculer based project on a k8s cluster.

Thanks!!

**Comment by icebob** [comment]
The built-in Prometheus metric exporter exposes the metrics via a HTTP port, and you can collect it with some k8s annotations:

```yml
 spec:                                                                                                                                                                                                                                        
   template:                                                                                                                                                                                                                               
     metadata:                                                                                                                                                                                                                             
       annotations:                                                                                                                                                                                                                        
         prometheus.io/path: /metrics                                                                                                                                                                                                      
         prometheus.io/port: "3030"                                                                                                                                                                                                        
         prometheus.io/scrape: "true"                                                                                                                                                                                                      
```
