### ISSUE TITLE
A way to destructure services into individual Docker images

### ISSUE THREAD

**Issue by amroessam** [moleculerjs/moleculer#568]
**Is your feature request related to a problem? Please describe.**
Building Docker images is a problem. As of now, we have github repos for each service. So we can build docker images individually.

**Describe the solution you'd like**
However, we'd like a way for moleculer to be able to destructure the services folder into separate docker builds.

**Describe alternatives you've considered**
We're currently working on a repo/service structure, which is not very efficient.

**Comment by amroessam** [comment]
Tagging the team @kamilkamili @mohammed-ali-1

**Comment by amroessam** [comment]
@icebob @AndreMaz @faeron @Nathan-Schwartz @shawnmcknight, I created a cli tool [moldock](https://github.com/amroessam/moldock) that does that, please take a look and advice the way forward. It's currently not up on npm due to some issues with my account but should be resolved shortly.
You can clone the project and do and `npm i -g .` then use it as the doc sys.

**Comment by icebob** [comment]
Good job @amroessam! I will check it as soon as I can.

**Comment by lucduong** [comment]
@amroessam @icebob 

That could be great when separating services to many projects. It can be easy and usefull when you're working in remote team and you want to keep other modules secret.

I have completed my project with another approach.

### My Project information:
- More than 1 million USD budget.
- About billion of data using PostgreSQL cluster.
- More than 30 services.
- GraphQL
- Moleculer Framework.
- VueJS for client

### Project Structure:
```
├── CHANGELOG.md
├── CONTRIBUTING.md
├── README.md
├── packages
│   ├── admin
│   ├── client
│   │   ├── src
│   │   ├── tsconfig.json
│   │   ├── tslint.json
│   │   ├── vue.config.js
│   │   └── yarn.lock
│   ├── docs
│   │   ├── Dockerfile
│   │   ├── package.json
│   │   ├── src
│   └── server
│       ├── Dockerfile
│       ├── dist
│       │   ├── moleculer.config.js
│       │   ├── package.json
│       │   ├── src
│       │   │   └── services
│       │   │       ├── ais
│       │   │       │   ├── cron.service.js
│       │   │       │   ├── graphile.service.js
│       │   │       ├── api
│       │   │       │   └── index.service.js
│       │   │       ├── authorizer
│       │   │       │   └── index.service.js
│       │   │       ├── user
│       │   │       │   ├── configUser.service.js
│       │   │       │   ├── graphile.service.js
│       │   │       │   ├── userTeam.service.js
│       │   │       │   └── userWatchList.service.js
│       │   │       └── xx-filter
│       │   │           ├── graphile.service.js
│       │   │           └── xx-filter.service.js
│       │   └── yarn.lock
│       ├── moleculer.config.ts
│       ├── package.json
│       ├── playground
│       ├── src
│       │   ├── @types
│       │   │   ├── sometype
│       │   │   │   └── index.d.ts
│       │   │   ├── common.d.ts
│       │   │   └── moleculer-graphql
│       │   │       └── index.d.ts
│       │   ├── core
│       │   │   ├── BaseService.ts
│       │   │   └── constans.ts
│       │   ├── graphql
│       │   │   └── fragment
│       │   │       └── vessel.graphql
│       │   ├── mail-template
│       │   │   ├── aor-notification.html
│       │   │   ├── demo.html
│       │   │   └── img
│       │   │       └── vts-logo.png
│       │   ├── mixins
│       │   │   ├── gql-query.mixin.ts
│       │   │   ├── graphql.mixin.ts
│       │   │   └── utils.ts
│       │   ├── register
│       │   │   └── graphql
│       │   │       └── index.js
│       │   ├── services
│       │   │   ├── api
│       │   │   │   ├── index.service.ts
│       │   │   │   └── utils.ts
│       │   │   ├── authorizer
│       │   │   │   └── index.service.ts
│       │   │   └── xx-filter
│       │   │       └── xx-filter.service.ts
│       │   └── tests
│       │       ├── some.spec.ts
│       ├── tsconfig.json
│       ├── tslint.json
│       ├── webpack.config.js
│       └── yarn.lock
├── provision
│   ├── swarmpit.yml
│   ├── swarmprom.yml
│   ├── traefik.toml
│   └── traefik.yml
└── XX
```

### Service structure
We used TypeScript so it looks quite complicated. Anyway, the basic concept about services is:
- We located all services in `services` folder.
- One `group` of service will be one folder.
- One `group` can contains only one service. Which named as `index.service.{ts|js}`

### Deployment
- We used docker swarm for our deployment.
- One service (or group of service) will be running in 1 or multiple containers.
- We have only one server images, not separated as many images. All service will be using one server image.
	> First time, we though, one service should be one image but it quite difficult to manage. And it won't reduce the total size of images in registry.
- We bundle the project by using `webpack bundler`.
	> After bundling: The `dist` will look like above project structure (in `dist` part)
- The key point to run individual service is about choosing the service folder.
	`node -r dotenv/config node_modules/.bin/moleculer-runner services/service_folder_name`
- Our example `yaml` file of each service:
```yaml
version: "3.5"
services:
  acl:
    image: asia.gcr.io/ltvcoffee/server:0.1.0
    command:
      - yarn
      - start:prod
      - services/acl
    environment:
      NODE_ENV: production
      NODE_ID: lc_node_acl
    secrets:
      - source: env
        target: /app/.env
    networks:
      - lc_postgres
      - lc_nats
      - lc_redis
    logging:
      driver: json-file
      options:
        max-size: 50m
    deploy:
      update_config:
        parallelism: 2
        delay: 0s
        order: start-first
networks:
  lc_postgres:
    external: true
  lc_nats:
    external: true
  lc_redis:
    external: true
secrets:
  env:
    name: lc_env
    external: true
```
- We deploy as a stack
```bash
docker stack deploy -c ./api-gateway.yml --with-registry-auth lc
docker stack deploy -c ./acl.yml --with-registry-auth lc
docker stack deploy -c ./authorizer.yml --with-registry-auth lc
```
- When we want to update individual service, only run
```
docker stack deploy -c ./acl.yml --with-registry-auth lc
```
- When we want to know which service should be updating
	We wrote some shell script code to check which changes in the code to determine which service should be deployment. 

### TOBE Sharing
Above is only about small thing in our project and our team experience.
I hope to have time to share with all of you guys.
But, the best way to share is based on your questions.
