### ISSUE TITLE
Apparently moleculer cannot write a log inside the docker container

### ISSUE THREAD

**Issue by developez** [moleculerjs/moleculer#894]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [ ] I am running the latest version
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository

## Current Behavior

No log file is writed in the folder.

## Expected Behavior

Log file writed in a folder.

## Failure Information

No failure information, only the console log works.

This configuration works when I run the project without docker.

### Steps to Reproduce

Inside the moleculer.config.ts

```
logger: [
		{
            type: "Console",
            options: {
                level: "info",
            }
        },
        {            
            type: "File",
            options: {
                level: "info",
                folder: "/logs/moleculer",
                filename: "all.log",
                formatter: "{timestamp} {level} {nodeID}/{mod}: {msg}"
            }
        },
	],
```

DockerFile

```
FROM node:lts-alpine

# Working directory
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json ./
RUN npm ci --silent

# Copy source
COPY . .

# Build and cleanup
ENV NODE_ENV=production
RUN npm run build \
 && npm prune

# Start server
CMD ["node", "./node_modules/moleculer/bin/moleculer-runner.js"]
```

docker-compose.yml

```
version: "3.3"

services:

  api:
    restart: always
    build:
      context: .
    image: foo-connect-platform:1.0.0.0
    #container_name: foo-connect-platform
    env_file: docker-compose.env
    environment:
      SERVICES: api,$node,message-logs,message-processor,tcp-endpoint
    #depends_on:
    #  - redis
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=8090"
    networks:
      - internal
    ports: 
      - "8090:8090"
      - "8091:8091"
      - "8092:8092"  

networks:
  internal:
    internal: false
```
